### ISSUE TITLE
Add a wiki: NintendoWiki

### ISSUE THREAD

**Issue by ferryszhtan81** [KevinPayravi/indie-wiki-buddy#343] opened 2023-11-15 12:11 UTC
Link to origin wiki: https://nintendo.fandom.com
Link to destination (independent) wiki: https://niwanetwork.org/

**Comment by KevinPayravi** [comment] 2023-11-16 15:29
Unfortunately won't be redirecting this one as there is a huge content gap. The Nintendo Fandom Wiki has over 37,000 articles, vs 2,400 on Nintendo Wiki.

_(Note, duplicate of https://github.com/KevinPayravi/indie-wiki-buddy/issues/80)_

**Closed by KevinPayravi** 2023-11-16 15:29 UTC
Labels: add wiki
