### ISSUE TITLE
Add a wiki: Undertale Yellow Wiki

### ISSUE THREAD

**Issue by WonderfulProgress** [KevinPayravi/indie-wiki-buddy#454] opened 2024-01-29 22:43 UTC
Link to origin wiki: [Fandom](https://undertaleyellow.fandom.com/wiki/Undertale_Yellow_Wiki)
Link to destination (independent) wiki: [Wiki.gg]( https://undertaleyellow.wiki.gg/wiki/Undertale_Yellow_Wiki)

**Comment by KevinPayravi** [comment] 2024-01-29 22:44
Duplicate of https://github.com/KevinPayravi/indie-wiki-buddy/issues/453, will be in the next update soon!

**Closed by KevinPayravi** 2024-01-29 22:44 UTC
Labels: add wiki
