### ISSUE TITLE
Add a wiki: TARDIS (Doctor Who) Wiki

### ISSUE THREAD

**Issue by ayyLumao** [KevinPayravi/indie-wiki-buddy#518] opened 2024-02-25 23:54 UTC
Link to origin wiki: https://tardis.wiki/wiki/Doctor_Who_Wiki
Link to destination (independent) wiki: https://tardis.wiki/wiki/Doctor_Who_Wiki

**Comment by KevinPayravi** [comment] 2024-02-26 00:10
Duplicate of https://github.com/KevinPayravi/indie-wiki-buddy/issues/516, has been added and will be in the next release.

**Closed by KevinPayravi** 2024-02-26 00:10 UTC
Labels: add wiki
