### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by BabylonAS** [KevinPayravi/indie-wiki-buddy#515] opened 2024-02-25 10:19 UTC
With seventeen languages supported for wikis and counting, it's pretty obvious that the extension needs its UI to be translatable. If and when IWB adds localization support, I'd gladly provide the Russian translation for it!

**Comment by SnorlaxMonster** [comment] 2024-02-26 06:23
I think this is effectively a duplicate of #31 (the oldest open Issue).

**Comment by BabylonAS** [comment] 2024-02-26 07:08
I didn't notice it, probably because I was looking for “localization” and “internationalization”, not “translation”.

**Closed** 2024-02-26 08:11 UTC
Labels: status: duplicate, type: new feature
