### ISSUE TITLE
Add a wiki: Rhythm Doctor

### ISSUE THREAD

**Issue by wolfplay013** [KevinPayravi/indie-wiki-buddy#285] opened 2023-11-01 09:24 UTC
Link to origin wiki: https://rhythm-doctor.fandom.com/wiki/Rhythm_Doctor_Wiki
Link to destination (independent) wiki: https://wiki.rhythm.cafe/page/Main_Page

**Comment by chocmake** [comment] 2023-11-02 04:14
Seems to be dupe of #213

**Comment by wolfplay013** [comment] 2023-11-02 18:46
ah gotcha.

**Closed** 2023-11-27 08:56 UTC
Labels: add wiki
