### ISSUE TITLE
Add a wiki: Terraria

### ISSUE THREAD

**Issue by Thrasher146** [KevinPayravi/indie-wiki-buddy#398] opened 2023-12-24 15:26 UTC
Link to origin wiki: https://terraria.fandom.com/wiki/Terraria_Wiki
Link to destination (independent) wiki: https://terraria.wiki.gg

**Comment by KevinPayravi** [comment] 2023-12-25 08:19
Dupe of https://github.com/KevinPayravi/indie-wiki-buddy/issues/242 - The Terraria Wiki.gg wiki as been added to the extension but the update is pending release (needs to be reviewed by the Firefox store, which might take longer than usual due to the holidays)

**Closed by KevinPayravi** 2023-12-25 08:19 UTC
Labels: add wiki
